// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/a134b0d05156a02d4119c1e0c790c6fe4e9f896a/gsap/index.d.ts

/// <reference path="Animation.d.ts"/>
/// <reference path="Ease.d.ts"/>
/// <reference path="TweenConfig.d.ts"/>
/// <reference path="Tween.d.ts"/>
/// <reference path="Timeline.d.ts"/>
/// <reference path="Plugins.d.ts"/>

declare module 'gsap' {
    export = gsap;
}
